config/routes.rb
Rails.application.routes.draw do
  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resource :search, only: [:show]

  resources :posts, only: [:index, :update, :destroy, :show, :edit] do
    resource :spam, only: [:create]
    resources :images, only: [:new, :create]
  end

  resources :locations, only: [:new, :create, :index, :show] do
    resources :categories, only: [:show, :new, :create, :index]
    resources :posts, only: [:create]
  end

  get "/sign_in", to: "sessions#new"
  get "/sign_up", to: "users#new"

  root to: "posts#index"
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true

  has_many :post_categories
  has_many :posts, through: :post_categories

  belongs_to :locations 
end

app/models/guest.rb
class Guest
  def admin?
    false
  end

  def logged_in?
    false
  end

  def posts
    Post.none
  end

  def id
    -1
  end
end

app/models/location.rb
class Location < ActiveRecord::Base
  MAX_CATEGORIES_DISPLAYED = 5
  validates :name, presence: true, uniqueness: true

  has_many :categories
  has_many :posts
  has_many :images, through: :posts

  def featured_categories
    categories.limit(MAX_CATEGORIES_DISPLAYED)
  end 

  def self.alphabetical
    order(:name)
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true
  validates :body, presence: true
  validates :user, presence: true
  validates :location, presence: true
  validates :price, presence: true

  belongs_to :user
  belongs_to :location
  belongs_to :category

  has_many :post_categories
  has_many :categories, through: :post_categories

  def self.order_by_time
    order("created_at DESC")
  end

  def self.spam
    where(spam: true)
  end
end

app/models/post_category.rb
class PostCategory < ActiveRecord::Base
  belongs_to :category
  belongs_to :post

  validates :category_id, presence: true
  validates :post, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, presence: true, uniqueness: true
  validates :password_digest, presence: true

  has_many :posts

  def allowed_to_modify_post?(post)
    admin? || post_owner?(post)
  end

  private

  def post_owner?(post)
    post.user_id == id
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Monban::ControllerHelpers
  protect_from_forgery with: :exception

  def current_user
    super || Guest.new
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @location = Location.find(params[:location_id])
    @category = Category.new
  end

  def create
    @location = Location.find(params[:location_id])
    @category = @location.categories.new(category_params)
    @category.name = @category.name.capitalize
    if @category.save
      redirect_to @location
    else
      render :new
    end
  end

  def show
    @location = Location.find(params[:location_id])
    @category = Category.find(params[:id])
    @posts = @category.posts
  end

  private

  def category_params
    params.require(:category).permit(
      :name,
      :id,
    )
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def index
    @locations = Location.order(:name)
    @location = Location.new
    @spam = Post.spam
  end

  def show
    @location = Location.find(params[:id])
    @post = Post.new
    @posts = @location.posts
  end

  def create
    @locations = Location.all
    @location = Location.new(location_params)
    @location.name = @location.name.capitalize

    if @location.save
      redirect_to :locations
    else
      render :new
    end
  end

  private

  def location_params
    params.require(:location).permit(
      :name,
    )
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :require_login, only: [:create, :edit, :update]

  def index
    @spam = Post.where(spam: true)
    @posts = Post.order_by_time.page(params[:page])
    @locations = Location.order(:name)
  end

  def show
    @user = current_user
    @post = Post.find(params[:id])
    @location = @post.location 
  end

  def create
    @location = Location.find(params[:location_id])
    @post = current_user.posts.new(post_params.merge(location_id: @location.id))
    @post.title = @post.title.capitalize

    if @post.save
      redirect_to @location
    else
      @categories = Category.all
      @posts = Post.all
      @locations = Location.all
      render "locations/show"
    end
  end

  def edit
    @post = Post.find(params[:id])
    if current_user.allowed_to_modify_post?(@post)
      @locations = Location.all
    else
      redirect_to :posts
    end
  end

  def update
    @post = Post.find(params[:id])
    if current_user.allowed_to_modify_post?(@post)
      if @post.update(post_params)
        redirect_to @post
      else
        render :edit
      end
    else
      redirect_to :posts
    end
  end

  def destroy
    post = Post.find(params[:id])
    if current_user.allowed_to_modify_post?(post)
      post.destroy
      redirect_to :posts
    else
      redirect_to :posts
    end
  end

  private

  def post_params
    params.require(:post).permit(
      :title,
      :body,
      :price,
      :image_url,
      category_ids: [],
    )
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def show
    @found_results= run_search
  end

  private
  
  def run_search
    Post.where("title ILIKE :search OR body ILIKE :search", search: "%#{params[:search]}%")
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
  end

  def create
    user = authenticate_session(session_params)

    if sign_in(user)
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to [:new, :session]
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end
end

app/controllers/spams_controller.rb
class SpamsController < ApplicationController
  def create
    post = Post.find(params[:post_id])
    post.update_attributes(:spam => true)

    redirect_to :posts
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = sign_up(user_params)
    if @user.valid?
      sign_in(@user)
      redirect_to root_path
    else
      render :new
    end
  end

  def show
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_create_post.html.erb
<%= form_for [@location, @post] do |form| %>
  <%= render "error_messages", target: @post %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>
  <div>
    <p class="form-label">Ad categories</p>
    <%= form.collection_check_boxes(:category_ids, @location.categories, :id, :name) %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/application/_error_messages.html.erb
<div>
  <% if target.errors.any? %>
    <h3>
      <%= pluralize target.errors.count, "error" %> 
      prevented this form from saving: 
    </h3>
    <ul>
      <% target.errors.full_messages.each do |message| %>
        <li class="error_text"><h3><%= message %></h3></li>
      <%end%> 
    </ul>
  <% end %>
</div>

app/views/categories/new.html.erb
<h2>Create a new category</h2>

<%= form_for [@location, @category] do |form| %>
  <%= render "error_messages", target: @category %>
  <div>
    <%= form.label :name, "Category Name" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.submit :submit %>
  </div>
<% end %>

app/views/categories/show.html.erb
<h3> Posts in <%= @location.name %> under the <%= @category.name %> category </h3>
<ul>
  <% @posts.each do |post| %>
    <li> <%= link_to post.title, post %> </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Trading Tree</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if signed_in? %>
    <% if current_user.admin? %>
      <div class="sign-out">You are signed in as an ADMIN <%= link_to "Sign out", :session, method: :delete %></div>
    <% else %>
      <div class="sign-out">You are signed in as <%= current_user.email %> <%= link_to "Sign out", :session, method: :delete %></div>
  <% end %>
  <% elsif %>
    <div class = "sign-out">
      <%= link_to "Create new account", sign_up_path %>
      <%= link_to "Sign in", sign_in_path %>
    </div>
  <% end %>

  <h1> Trading Tree </h1>

  <div class="outer-container">
    <div class="left-container">
      <div class="quick-links">
        <h2>Quick Links</h2>
        <% if signed_in? %>
          <div><%= link_to "My Posts", current_user %></div>
        <% end %>
        <div><%= link_to "See All Locations", :locations %></div>
        <div><%= link_to "All Posts", :posts %></div>
        <div class="search">
          <%= form_tag("/search", method: "get") do %>
            <%= label_tag(:search, "Search All Posts:") %>
            <%= text_field_tag(:search) %>
            <%= submit_tag "Search", name: nil %>
          <% end %>
        </div>
      </div>
      <%= content_for :left_container %>
    </div>
    <div class="main-dashboard">
      <%= yield %>
    </div>
  </div> 
</body>
</html>

app/views/locations/_admin_delete_spam.html.erb
<h3>Spam</h3>
<p>The following posts have been marked by users as spam.  Delete as you see fit.</p>
</ul>
  <% @spam.each do |spam| %>
    <li> 
      <%= spam.title %>
      <%= button_to "Delete this Spam", spam, method: :delete %>
    </li>
  <% end %>
</ul>

app/views/locations/index.html.erb
<ul>
  <% @locations.alphabetical.each do |location| %>
    <li class="location-list">
      <%= link_to location.name, location %>
      <ul>
        <% location.featured_categories.each do |category| %>
          <li class="category-list"><%= link_to category.name, [location, category] %></li>
        <% end %>
      </ul>
    </li>
  </ul>
  <% end %>

<% if current_user.admin? %>
  <div class="admin_section">
    <h2>Administration</h2>
    <h3>Add a Location</h3>
    <%= form_for @location do |form| %>
      <%= render "error_messages", target: @location %>
      <div>
        <%= form.label :name, "Location" %>
        <%= form.text_field :name %>
      </div>
      <div>
        <%= form.submit "Add Location" %>
      </div>
    <% end %>

    <%= render 'admin_delete_spam' %>
  </div>
<% end %>

<% if signed_in? %>
  <% content_for :left_container do %>
    <div class="new-post-dash">
      <h2>Post an Ad</h2>
        <p class="form-label">Locations</p>
          <%= collection_select(
            :location,
            :id, 
            @locations, 
            :id, 
            :name, 
            include_blank: "choose..." 
          ) %>
        <a id="choose_location" href="">Choose Location</a>
    </div>   
  <% end %>
<% end %>

app/views/locations/show.html.erb
<% if signed_in? %>
  <% content_for :left_container  do %>
    <div class="new-post-dash">
      <h2> Post an Ad </h2>
      <div><%= render "create_post" %></div>
    </div>
  <% end %>
<% end %>

<h2>Ads in <%= @location.name %></h2>
<ul>
  <% @posts.each do |post| %>
    <li><%= link_to post.title, post %></li>
  <% end %>
</ul>
<h2> Catagories in <%= @location.name %> </h2>
<ul>
  <% @location.categories.each do |category| %>
    <li>
      <%= link_to category.name, [@location, category] %>
    </li>
  <% end %>
</ul>
 <% if current_user.admin? %>
    <div class="admin_section"><h3>Administration</h3>
      <%= button_to "Create category", [:new, @location, :category], method: :get %>
    </div>
  <% end %>

app/views/posts/_edit_post.html.erb
<%= form_for @post do |form| %>
  <%= render "error_messages", target: @post %>
  <div>
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>
  <div>
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>
  <div>
    <%= form.label :image_url %>
    <%= form.text_field :image_url %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/_report_spam_button.html.erb
<%= button_to "Mark as Spam", [post, :spam], method: :post %>

app/views/posts/edit.html.erb
<h2>Current Post</h2>
<div>
  <%= @post.title %>
</div>
<div>
  <%= @post.body %>
</div>
<div>
  <%= @post.price %>
</div>
<div>
  <%= @post.location.name %>
</div>

<% if signed_in? %>
  <h2>Edit  Post</h2>
  <div><%= render "edit_post" %></div>
  <%= button_to "Delete Post", @post, method: :delete %>
<% end %>

app/views/posts/index.html.erb
<% if signed_in? %>
  <% content_for :left_container  do %>
    <div class="new-post-dash">
      <h2> Post an Ad </h2>
      <%= link_to "Go to locations page", :locations %>
    </div>
  <% end %>
<% end %>

<ul>
  <% @locations.each do |location| %>
    <li>
      <h2><%= location.name %></h2>
      <ul>
        <% location.featured_categories.each do |category| %>
          <li><%= link_to category.name, [location, @category] %></li>
        <% end %>
      </ul>
    </li>
  <% end %>
</ul>

app/views/posts/show.html.erb
<div class="post_content_box">
  <h2><%= @post.title %></h2>
  <div>
    Description: <%= @post.body %> 
  </div>
  <div>
    Price: $<%= @post.price %> 
  </div>
  <div>
    Location: <%= @post.location.name %>
  </div>
  <div>
    <% if signed_in? %>
      <% if ! @post.spam? %>
        <%= render "report_spam_button", post: @post %>
      <% end %>
    <% end %>

    <% if @post.user_id == @user.id %>
      <%= button_to "Edit", [:edit, @post], method: :get %>
    <% end %>

    <div class="delete_button">
      <% if current_user.admin? %>
        <a name="spam_admin">
        <%= button_to "Delete Post", :post, method: :delete %>
      <% end %>
    </div>
  </div>
</div>
<div class="photo_box">
  <h2>Photo</h2>
  <img src="<%= @post.image_url %>" >
</div>

app/views/searches/show.html.erb
<h2>Search Results</h2>
  <% if @found_results.empty? %>
    <h3 class="label">No results found.</h3>
  <% else %>
    <ul>
    <% @found_results.each do |found_result| %>
    <li><%= link_to  found_result.title %></li>
    <% end %>
    </ul>
  <% end %>

app/views/users/new.html.erb
<h2>Create a new account</h2>
<%= form_for @user do |form| %>

  <% if @user.errors.any? %>
    <%= pluralize(@user.errors.count, "error") %> prevented your account from being created:
    <ul>
      <% @user.errors.full_messages.each do |error_message| %>
        <li><%= error_message %></li>
      <% end %>
    </ul>
  <% end %>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>
  <div>
    <%= form.submit "Sign up" %>
  </div>
<% end %>

app/views/users/show.html.erb
<h2 class ="top-page"> My Current Posts </h2>
<ul>
  <% current_user.posts.each do |post| %>
    <li><%= link_to post.title, post %></li>
  <% end %>
</ul>